### Numpy array

In [1]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [2]:
L = range(1_000)

In [3]:
%timeit [i**2 for i in L]

258 µs ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
a = np.arange(1_000)

In [5]:
%timeit a**2

1.16 µs ± 33.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [7]:
# looking 
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.char.array
    Create a `chararray`.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.from_dlpack
    Create a NumPy array from an object implementing the ``__dlpack__``
numpy.rec.fromarrays
    Create a record array from a (flat) list of arrays
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.rec.fromfile
    Create an array from binary file data
numpy.rec.fromstring
    Create a record array from binary data
numpy.lib.Arrayterator
    Buffered iterator for big 

In [8]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

In [ ]:
# import 
import numpy as np

#### Creating arrays

In [9]:
# 1-D:
a = np.array([0, 1, 2, 3])

print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3]
1
(4,)
4


In [10]:
# 2-D, 3-D, . . . :

b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array

print(b)
print(b.ndim)
print(b.shape)
print(len(b))

c = np.array([[[1], [2]], [[3], [4]]])

print(c.shape)

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2
(2, 2, 1)


In [11]:
# Evenly spaced:

a = np.arange(10) # 0 .. n-1 (!)
print(a)

b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [12]:
# or by number of points:

c = np.linspace(0, 1, 6) # start, end, num-points
print(c)

d = np.linspace(0, 1, 5, endpoint=False)
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [13]:
# Common arrays:
a = np.ones((3, 3)) # reminder: (3, 3) is a tuple

print(a)

b = np.zeros((2, 2))
print(b)

c = np.eye(3)
print(c)

d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
# np.random: random numbers (Mersenne Twister PRNG):

a = np.random.rand(4) # uniform in [0, 1]
print(a)

b = np.random.randn(4) # Gaussian
print(b)

np.random.seed(1234) # Setting the random seed

[0.25236789 0.20890441 0.70952992 0.67512895]
[ 0.35188469 -0.69440788  0.14447507 -0.40062699]


#### Basic data types

In [ ]:
>>> a = np.array([1, 2, 3])
>>> a.dtype
dtype('int64')
>>> b = np.array([1., 2., 3.])
>>> b.dtype
dtype('float64')

In [ ]:
>>> c = np.array([1, 2, 3], dtype=float)
>>> c.dtype
dtype('float64')

In [ ]:
>>> a = np.ones((3, 3))
>>> a.dtype
dtype('float64')

In [ ]:
Complex
>>> d = np.array([1+2j, 3+4j, 5+6*1j])
>>> d.dtype
dtype('complex128')

In [ ]:
Bool
>>> e = np.array([True, False, False, True])
>>> e.dtype
dtype('bool')

In [ ]:
Strings
>>> f = np.array(['Bonjour', 'Hello', 'Hallo'])
>>> f.dtype # <--- strings containing max. 7 letters
dtype('S7')

#### Basic visualization

In [ ]:
Once IPython has started, enable interactive plots:
>>> %matplotlib

In [ ]:
>>> import matplotlib.pyplot as plt # the tidy way

In [ ]:
>>> plt.plot(x, y) # line plot
>>> plt.show() # <-- shows the plot (not needed with interactive plots)

In [ ]:
>>> plt.plot(x, y) # line plot

In [ ]:
• 1D plotting:
>>> x = np.linspace(0, 3, 20)
>>> y = np.linspace(0, 9, 20)
>>> plt.plot(x, y) # line plot
[<matplotlib.lines.Line2D object at ...>]
>>> plt.plot(x, y, 'o') # dot plot
[<matplotlib.lines.Line2D object at ...>]

In [ ]:
• 2D arrays (such as images):
>>> image = np.random.rand(30, 30)
>>> plt.imshow(image, cmap=plt.cm.hot)
<matplotlib.image.AxesImage object at ...>
>>> plt.colorbar()
<matplotlib.colorbar.Colorbar object at ...>

#### Indexing and slicing

In [ ]:
>>> a = np.arange(10)
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> a[0], a[2], a[-1]
(0, 2, 9)

In [ ]:
>>> a[::-1]
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
>>> a = np.diag(np.arange(3))
>>> a
array([[0, 0, 0],
[0, 1, 0],
[0, 0, 2]])
>>> a[1, 1]
1
>>> a[2, 1] = 10 # third line, second column
>>> a
array([[ 0, 0, 0],
[ 0, 1, 0],
[ 0, 10, 2]])
>>> a[1]
array([0, 1, 0])

In [ ]:
>>> a = np.arange(10)
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> a[2:9:3] # [start:end:step]
array([2, 5, 8])

In [ ]:
>>> a[:4]
array([0, 1, 2, 3])

In [ ]:
>>> a[1:3]
array([1, 2])
>>> a[::2]
array([0, 2, 4, 6, 8])
>>> a[3:]
array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
>>> a[0, 3:5]
array([3, 4])
>>> a[4:, 4:]
array([[44, 55],
[54, 55]])
>>> a[:, 2]
a([2, 12, 22, 32, 42, 52])
>>> a[2::2, ::2]
array([[20, 22, 24],
[40, 42, 44]])

In [ ]:
>>> a = np.arange(10)
>>> a[5:] = 10
>>> a
array([ 0, 1, 2, 3, 4, 10, 10, 10, 10, 10])
>>> b = np.arange(5)
>>> a[5:] = b[::-1]
>>> a
array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#### Copies and views

In [ ]:
>>> a = np.arange(10)
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> b = a[::2]
>>> b
array([0, 2, 4, 6, 8])
>>> np.may_share_memory(a, b)
True
>>> b[0] = 12
>>> b
array([12, 2, 4, 6, 8])
>>> a # (!)
array([12, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> a = np.arange(10)
>>> c = a[::2].copy() # force a copy
>>> c[0] = 12
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> np

#### Fancy indexing

In [ ]:
Using boolean masks
>>> np.random.seed(3)
>>> a = np.random.randint(0, 21, 15)
>>> a
array([10, 3, 8, 0, 19, 10, 11, 9, 10, 6, 0, 20, 12, 7, 14])
>>> (a % 3 == 0)
array([False, True, False, True, False, False, False, True, False,
       True, True, False, True, False, False])
>>> mask = (a % 3 == 0)
>>> extract_from_a = a[mask] # or, a[a%3==0]
>>> extract_from_a # extract a sub-array with the mask
array([ 3, 0, 9, 6, 0, 12])

In [ ]:
>>> a[a % 3 == 0] = -1
>>> a
array([10, -1, 8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1, 7, 14])

In [ ]:
Indexing with an array of integers
>>> a = np.arange(0, 100, 10)
>>> a
array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
>>> a[[2, 3, 2, 4, 2]] # note: [2, 3, 2, 4, 2] is a Python list
array([20, 30, 20, 40, 20])

In [ ]:
>>> a[[9, 7]] = -100
>>> a
array([ 0, 10, 20, 30, 40, 50, 60, -100, 80, -100])

In [ ]:
>>> a = np.arange(10)
>>> idx = np.array([[3, 4], [9, 7]])
>>> idx.shape
(2, 2)
>>> a[idx]
array([[3, 4],
[9, 7]])

### Numerical operations on arrays

In [ ]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

### End.