### Numpy array

In [ ]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

In [ ]:
L = range(1_000)

In [ ]:
%timeit [i**2 for i in L]

In [ ]:
a = np.arange(1_000)

In [ ]:
%timeit a**2

In [ ]:
np.array?

In [ ]:
# looking 
np.lookfor('create array')

In [ ]:
np.con*?

In [ ]:
# import 
import numpy as np

#### Creating arrays

In [ ]:
# 1-D:
a = np.array([0, 1, 2, 3])

print(a)
print(a.ndim)
print(a.shape)
print(len(a))

In [ ]:
# 2-D, 3-D, . . . :

b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array

print(b)
print(b.ndim)
print(b.shape)
print(len(b))

c = np.array([[[1], [2]], [[3], [4]]])

print(c.shape)

In [ ]:
# Evenly spaced:

a = np.arange(10) # 0 .. n-1 (!)
print(a)

b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)

In [ ]:
# or by number of points:

c = np.linspace(0, 1, 6) # start, end, num-points
print(c)

d = np.linspace(0, 1, 5, endpoint=False)
print(d)

In [ ]:
# Common arrays:
a = np.ones((3, 3)) # reminder: (3, 3) is a tuple

print(a)

b = np.zeros((2, 2))
print(b)

c = np.eye(3)
print(c)

d = np.diag(np.array([1, 2, 3, 4]))
print(d)

In [ ]:
# np.random: random numbers (Mersenne Twister PRNG):

a = np.random.rand(4) # uniform in [0, 1]
print(a)

b = np.random.randn(4) # Gaussian
print(b)

np.random.seed(1234) # Setting the random seed

#### Basic data types

In [ ]:

a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

In [ ]:

c = np.array([1, 2, 3], dtype=float)
print(c.dtype)

In [ ]:
a = np.ones((3, 3))
print(a.dtype)

In [ ]:
# Complex

d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

In [ ]:
# Bool

e = np.array([True, False, False, True])
print(e.dtype)

In [ ]:
# Strings

f = np.array(['Bonjour', 'Hello', 'Hallo'])
print(f.dtype)

#### Basic visualization

In [ ]:
# Once IPython has started, enable interactive plots:

%matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:

plt.plot(x, y) # line plot
plt.show() # <-- shows the plot (not needed with interactive plots)

In [ ]:
plt.plot(x, y) # line plot

In [ ]:
# 1D plotting:
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)

plt.plot(x, y) # line plot
plt.plot(x, y, 'o') # dot plot

In [ ]:
# 2D arrays (such as images):

image = np.random.rand(30, 30)
plt.imshow(image, cmap=plt.cm.hot)

plt.colorbar()

#### Indexing and slicing

In [ ]:
a = np.arange(10)

print(a)
a[0], a[2], a[-1]

In [ ]:
a[::-1]

In [ ]:
a = np.diag(np.arange(3))

print(a)
print(a[1, 1])

a[2, 1] = 10 # third line, second column

print(a)
print(a[1])

In [ ]:
a = np.arange(10)

print(a)

print(a[2:9:3])

In [ ]:
print(a[:4])

In [ ]:

print(a[1:3])

print(a[::2])

print(a[3:])

In [ ]:
print(a[0, 3:5])

print(a[4:, 4:])

print(a[:, 2])

print(a[2::2, ::2])

In [ ]:
a = np.arange(10)
a[5:] = 10
print(a)

b = np.arange(5)
a[5:] = b[::-1]
print(a)

#### Copies and views

In [ ]:
a = np.arange(10)

print(a)

b = a[::2]
print(b)

np.may_share_memory(a, b)
b[0] = 12

print(b)
print(a) # (!)

a = np.arange(10)

c = a[::2].copy() # force a copy
c[0] = 12

print(a)
print(np)

#### Fancy indexing

In [ ]:
# Using boolean masks

np.random.seed(3)
a = np.random.randint(0, 21, 15)

print(a)
print((a % 3 == 0))

mask = (a % 3 == 0)
extract_from_a = a[mask] # or, a[a%3==0]

print(extract_from_a) # extract a sub-array with the mask

In [ ]:

a[a % 3 == 0] = -1
print(a)

In [ ]:
# Indexing with an array of integers

a = np.arange(0, 100, 10)
print(a)

In [ ]:

a[[2, 3, 2, 4, 2]] # note: [2, 3, 2, 4, 2] is a Python list

In [ ]:

a[[9, 7]] = -100
print(a)

In [ ]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])

print(idx.shape)

print(a[idx])

### Numerical operations on arrays

#### Elementwise operations

In [ ]:
With scalars:
>>> a = np.array([1, 2, 3, 4])
>>> a + 1
array([2, 3, 4, 5])
>>> 2**a
array([ 2, 4, 8, 16])

In [ ]:
All arithmetic operates elementwise:
>>> b = np.ones(4) + 1
>>> a - b
array([-1., 0., 1., 2.])
>>> a * b
array([2., 4., 6., 8.])
>>> j = np.arange(5)
>>> 2**(j + 1) - j
array([ 2, 3, 6, 13, 28])

In [ ]:
These operations are of course much faster than if you did them in pure python:
>>> a = np.arange(10000)
>>> %timeit a + 1
10000 loops, best of 3: 24.3 us per loop
>>> l = range(10000)
>>> %timeit [i+1 for i in l]
1000 loops, best of 3: 861 us per loop

In [ ]:
>>> c.dot(c)
array([[3., 3., 3.],
[3., 3., 3.],
[3., 3., 3.]])

In [ ]:
Comparisons:
>>> a = np.array([1, 2, 3, 4])
>>> b = np.array([4, 2, 2, 4])
>>> a == b
array([False, True, False, True])
>>> a > b
array([False, False, True, False])

In [ ]:
Tip: Array-wise comparisons:
>>> a = np.array([1, 2, 3, 4])
>>> b = np.array([4, 2, 2, 4])
>>> c = np.array([1, 2, 3, 4])
>>> np.array_equal(a, b)
False
>>> np.array_equal(a, c)
True

In [ ]:
Logical operations:
>>> a = np.array([1, 1, 0, 0], dtype=bool)
>>> b = np.array([1, 0, 1, 0], dtype=bool)
>>> np.logical_or(a, b)
array([ True, True, True, False])
>>> np.logical_and(a, b)
array([ True, False, False, False])
>>> a = np.arange(5)
>>> np.sin(a)
array([ 0. , 0.84147098, 0.90929743, 0.14112001, -0.7568025 ])
>>> np.log(a)
array([ -inf, 0. , 0.69314718, 1.09861229, 1.38629436])
>>> np.exp(a)
array([ 1. , 2.71828183, 7.3890561 , 20.08553692, 54.59815003])

In [ ]:
Shape mismatches
>>> a = np.arange(4)
>>> a + np.array([1, 2])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (4) (2)

In [ ]:
Transposition:
>>> a = np.triu(np.ones((3, 3)), 1) # see help(np.triu)
>>> a
array([[0., 1., 1.],
[0., 0., 1.],
[0., 0., 0.]])
>>> a.T
array([[0., 0., 0.],
[1., 0., 0.],
[1., 1., 0.]])

In [ ]:
The transpose returns a view of the original array:
>>> a = np.arange(9).reshape(3, 3)
>>> a.T[0, 2] = 999
>>> a.T
array([[ 0, 3, 999],
[ 1, 4, 7],
[ 2, 5, 8]])
>>> a
array([[ 0, 1, 2],
[ 3, 4, 5],
[999, 7, 8]])

#### Basc reductions

In [ ]:
Computing sums
>>> x = np.array([1, 2, 3, 4])
>>> np.sum(x)
10
>>> x.sum()

In [ ]:
Sum by rows and by columns:
>>> x = np.array([[1, 1], [2, 2]])
>>> x
array([[1, 1],
[2, 2]])
>>> x.sum(axis=0) # columns (first dimension)
array([3, 3])
>>> x[:, 0].sum(), x[:, 1].sum()
(3, 3)
>>> x.sum(axis=1) # rows (second dimension)
array([2, 4])
>>> x[0, :].sum(), x[1, :].sum()
(2, 4)

In [ ]:
Tip: Same idea in higher dimensions:
>>> x = np.random.rand(2, 2, 2)
>>> x.sum(axis=2)[0, 1]
1.14764...
>>> x[0, 1, :].sum()

In [ ]:
Extrema:
>>> x = np.array([1, 3, 2])
>>> x.min()
1
>>> x.max()
>>> x.argmin() # index of minimum
0
>>> x.argmax() # index of maximum

In [ ]:
Logical operations:
>>> np.all([True, True, False])
False
>>> np.any([True, True, False])
True

In [ ]:
>>> a = np.zeros((100, 100))
>>> np.any(a != 0)
False
>>> np.all(a == a)
True
>>> a = np.array([1, 2, 3, 2])
>>> b = np.array([2, 2, 3, 2])
>>> c = np.array([6, 4, 4, 5])
>>> ((a <= b) & (b <= c)).all()
True

In [ ]:
Statistics:
>>> x = np.array([1, 2, 3, 1])
>>> y = np.array([[1, 2, 3], [5, 6, 1]])
>>> x.mean()
1.75
>>> np.median(x)
1.5
>>> np.median(y, axis=-1) # last axis
array([2., 5.])
>>> x.std() # full population standard dev.
0.82915619758884995

#### Broadcasting

In [ ]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

### End.